spring.application.name=alchemy

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5-coder:1.5b
spring.ai.ollama.embedding.options.model=qwen3-embedding:0.6b

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=150MB

qdrant.url=http://localhost:6333
qdrant.collection=priyanshi

spring.data.redis.host=localhost
spring.data.redis.port=6379

app.cache.ttl-days=30
app.cache.similarity-threshold=0.88
app.cache.vector-dimension=768
app.cache.admission-threshold=2

app.memory.max-messages=20
app.memory.ttl-days=7

# JWT secret should be long.
# Later production me env variable use karna.
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

# MySQL configuration environment variables se aayegi.
# Isse real credentials GitHub par expose nahi honge.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/alchemy