spring.application.name=alchemy
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5-coder:1.5b-base
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
qdrant.url=http://localhost:6333
qdrant.collection=priyanshi
spring.redis.host=localhost
spring.redis.port=6379